cag/urls.py
#coding=utf-8
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^empresa/$', views.empresas, name="empresas"),
    url(r'^regional/$', views.regionais, name="regionais"),
    url(r'^baseregional/$', views.basesregionais, name="basesregionais"),
    url(r'^pex/$', views.tipos, name="tipos"),
    url(r'^pex/pas/$', views.pas, name="pas"),
    url(r'^infraestrutura/link/$', views.links, name="links"),
    url(r'^agencias/$', views.agencias, name="agencias"),
    url(r'^agencias/detalhes/(?P<pk>[\w_-]+)/$', views.agencia_detalhes, name="agencia_detalhes"),
]

cat/urls.py
#coding=utf-8
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^cargo/$', views.cargos, name="cargos"),
    # url(r'^cargo/add/$', views.add_cargo, name="add_cargo"),
    url(r'^pessoa/$', views.pessoas, name="pessoas"),
    url(r'^atendente/$', views.atendentes, name="atendentes"),
]

ctr/urls.py
#coding=utf-8
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^treinamento/$', views.treinamentos, name="treinamentos"),
    url(r'^treinamento/inicial/add/$', views.treinamento_inicial_add, name="treinamento_inicial_add"),
    url(r'^treinamento/inicial/update/(?P<pk>\d+)/$', views.treinamento_inicial_update, name='treinamento_inicial_update'),
    url(r'^treinamento/rotina/add/$', views.treinamento_rotina_add, name="treinamento_rotina_add"),
    url(r'^treinamento/rotina/update/(?P<pk>\d+)/$', views.treinamento_rotina_update,
        name='treinamento_rotina_update'),
    url(r'^matriculados/(?P<treinamento_pk>\d+)/$', views.matriculas_treinamento, name='avaliar_treinamento'),
    url(r'^matriculado/(?P<pk>\d+)/treinamento/(?P<treinamento_pk>\d+)/$', views.avaliar_matriculado, name='avaliar_matriculado'),
    url(r'^pesquisa_matricula/$', views.pesquisa_matricula, name='pesquisa_matricula'),
]

gestao/urls.py
#coding=utf-8
from copy import name

from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.views.static import serve as serve_static

from core import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^controle_agencias/', include('cag.urls', namespace='cag')),
    url(r'^controle_pessoas/', include('cat.urls', namespace='cat')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^controle_treinamentos/', include('ctr.urls', namespace='ctr')),
    url(r'^admin/', admin.site.urls),
    url(r'^entrar/$', login, {'template_name' : 'login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page' : '/'}, name='logout'),    
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

core/models.py
# coding=utf-8
from django.db import models

class ControleTemporal(models.Model):
    dt_criado       = models.DateTimeField('Criado em', auto_now_add=True)
    dt_modificado   = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        abstract = True

core/views.py
# coding=utf-8
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.shortcuts import render

class IndexView(LoginRequiredMixin, TemplateView):

    template_name = 'index.html'

index = IndexView.as_view()

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <!-- META SECTION -->
    <title>Sistema de Gestão</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <link rel="icon" href="{% static "favicon.ico" %}" type="image/x-icon"/>
    <!-- END META SECTION -->

    <link rel="stylesheet" type="text/css" href="{% static "css/jquery/jquery-ui.min.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap/bootstrap.min.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/fontawesome/font-awesome.min.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/summernote/summernote.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/codemirror/codemirror.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/nvd3/nv.d3.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/mcustomscrollbar/jquery.mCustomScrollbar.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/fullcalendar/fullcalendar.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/blueimp/blueimp-gallery.min.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/rickshaw/rickshaw.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/dropzone/dropzone.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/animate/animate.min.css" %}"/>

    <!-- CSS INCLUDE -->
    <link rel="stylesheet" type="text/css" id="theme" href="{% static "css/theme-default.css" %}"/>
    <!-- EOF CSS INCLUDE -->

    {% block css_or_script_head %}{% endblock %}
</head>
<body>
<!-- START PAGE CONTAINER -->
<div class="page-container">

    <!-- START PAGE SIDEBAR -->
    <div class="page-sidebar">
        <!-- START X-NAVIGATION -->
        {% include 'sidebar_menu.html' %}
        <!-- END X-NAVIGATION -->
    </div>
    <!-- END PAGE SIDEBAR -->

    <!-- PAGE CONTENT -->
    <div class="page-content">

        <!-- START X-NAVIGATION VERTICAL -->
        {% include 'top.html' %}
        <!-- END X-NAVIGATION VERTICAL -->

        <!-- START BREADCRUMB -->
        <ul class="breadcrumb">
            {% block breadcrumb %}

                <li><a href="#">Home</a></li>
                <!--<li><a href="#">Tables</a></li>
                <li class="active">Data Tables</li>-->

            {% endblock %}
        </ul>
        <!-- END BREADCRUMB -->

        {% block messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endblock %}
        {% block container %} {% endblock %}

    </div>
    <!-- END PAGE CONTENT -->
</div>
<!-- END PAGE CONTAINER -->

<!-- MESSAGE BOX-->
<div class="message-box animated fadeIn" data-sound="alert" id="mb-signout">
    <div class="mb-container">
        <div class="mb-middle">
            <div class="mb-title"><span class="fa fa-sign-out"></span> <strong>Sair</strong> ?</div>
            <div class="mb-content">
                <p>Tem certeza que deseja sair?</p>
                <p>Pressione Não, se pretender continuar o trabalho. Pressione Sim para sair.</p>
            </div>
            <div class="mb-footer">
                <div class="pull-right">
                    <a href="{% url 'logout' %}" class="btn btn-success btn-lg">Sim</a>
                    <button class="btn btn-default btn-lg mb-control-close">Não</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END MESSAGE BOX-->

<!-- START PRELOADS -->
{% block preloads_body %}{% endblock %}
<!-- END PRELOADS -->

<!-- START SCRIPTS -->
<!-- START PLUGINS -->
<script type="text/javascript" src="{% static "js/plugins/jquery/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/plugins/jquery/jquery-ui.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/plugins/bootstrap/bootstrap.min.js" %}"></script>
<!-- END PLUGINS -->

<!-- THIS PAGE PLUGINS -->
<script type="text/javascript" src="{% static "js/plugins/icheck/icheck.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js" %}"></script>
{% block scripts_body %}{% endblock %}
<!-- END PAGE PLUGINS -->

<!-- START TEMPLATE -->

<script type="text/javascript" src="{% static "js/plugins.js" %}"></script>
<script type="text/javascript" src="{% static "js/actions.js" %}"></script>
<!-- END TEMPLATE -->
{% block code_scripts %} {% endblock %}
<!-- END SCRIPTS -->

</body>
</html>

core/templates/index.html
{% extends 'base.html' %}

{% block container %}
    <!-- PAGE TITLE -->
    <div class="page-title">
        <h2><span class="fa fa-arrow-circle-o-left"></span> Home</h2>
    </div>
    <!-- END PAGE TITLE -->

    <!-- PAGE CONTENT WRAPPER -->
    <div class="page-content-wrap">

        <div class="row">
            <div class="col-md-12">
                Bem-vindo ao Sistema de Gestão...
            </div>
        </div>
    </div>

{% endblock %}

core/templates/login.html
<!DOCTYPE html>
<html lang="en" class="body-full-height">
<head>
    {% load staticfiles %}
    {% load widget_tweaks %}
    <!-- META SECTION -->
    <title>Sistema de Gestão Estratégico</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <!-- END META SECTION -->

    <!-- CSS INCLUDE -->
    <link rel="stylesheet" type="text/css" href="{% static "css/jquery/jquery-ui.min.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap/bootstrap.min.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/fontawesome/font-awesome.min.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/summernote/summernote.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/codemirror/codemirror.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/nvd3/nv.d3.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/mcustomscrollbar/jquery.mCustomScrollbar.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/fullcalendar/fullcalendar.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/blueimp/blueimp-gallery.min.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/rickshaw/rickshaw.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/dropzone/dropzone.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/animate/animate.min.css" %}"/>
    <link rel="stylesheet" type="text/css" id="theme" href="{% static "css/theme-default.css" %}"/>
    <!-- EOF CSS INCLUDE -->

    <style>
        .login-container {
            position: absolute;
            top: -40px;
            left: -20px;
            right: -40px;
            bottom: 0%;
            width: auto;
            height: auto;
            background-image: url("{% static "assets/login/gestao-de-grafica-digital.png" %}");
            background-size: cover;
            z-index: 0;
        }
    </style>
</head>

<body>

<div class="login-container">

    <div class="login-box animated fadeInDown">
        {% comment %}<div class="login-logo"></div>{% endcomment %}
        <div class="login-body" style="margin-top: 20%">
            <div class="login-title"><strong>Bem-vindo</strong>, por favor entre</div>
            <form action="." class="form-horizontal" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="col-md-12">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <span class="fa fa-user" style="padding-bottom: 12px"></span>
                            </span>
                            {% render_field form.username|attr:"style: background: white; color: black" class="form-control" placeholder="Usuário" %}
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <span class="fa fa-lock" style="padding-bottom: 12px"></span>
                            </span>
                            {% render_field form.password|attr:"style: background: white; color: black" class="form-control" placeholder="Senha" %}
                        </div>
                    </div>
                </div>
                <div class="form-group">

                    <div class="col-md-6">
                        {% comment %}
                            <a href="#" class="btn btn-link btn-block">Forgot your password?</a>
                        {% endcomment %}
                    </div>

                    <div class="col-md-6">
                        <button class="btn btn-info btn-block"><span class="fa fa-unlock"></span>Entrar</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="login-footer">
        </div>
    </div>

</div>

</body>
</html>

core/templates/sidebar_menu.html
{% load staticfiles %}

<ul class="x-navigation">
    <li class="xn-logo">
        <a href="#">Gestão</a>
        <a href="#" class="x-navigation-control"></a>
    </li>
    <li class="xn-profile">
        <a href="#" class="profile-mini">
            {% if user.profile.avatar.url %}
                <img src="{{ user.profile.avatar.url }}" alt="{{ user }}"/>
            {% else %}
                <img src="{% static "assets/images/users/no-image.jpg" %}" alt="{{ user }}"/>
            {% endif %}
        </a>
        <div class="profile">
            <div class="profile-image">
            {% if user.profile.avatar.url %}
                <img src="{{ user.profile.avatar.url }}" alt="{{ user }}"/>
            {% else %}
                <img src="{% static "assets/images/users/no-image.jpg" %}" alt="{{ user }}"/>
            {% endif %}
            </div>
            <div class="profile-data">
                <div class="profile-data-name">{{ user }}</div>
            </div>
            <div class="profile-controls">
                <a href="{% url 'admin:index' %}" class="profile-control-left">
                    <span class="fa fa-key"></span>
                </a>
                <a href="{% url 'accounts:index' %}" class="profile-control-right">
                    <span class="fa fa-book"></span>
                </a>
            </div>
        </div>
    </li>
    <li class="xn-title">Navegação</li>
    <li class="xn-openable">
        <a href="#"><span class="fa fa-home"></span> <span class="xn-text">Presencial</span></a>
        <ul>
            <li>
                <a href="{% url 'cag:empresas' %}"><span class="fa fa-building-o"></span> <span
                        class="xn-text">Empresas</span></a>
            </li>
            <li><a href="{% url 'cag:regionais' %}"><span class="fa fa-globe"></span> Regionais</a></li>
            <li><a href="{% url 'cag:basesregionais' %}"><span class="fa fa-globe"></span> Bases Regionais</a></li>
            <li><a href="{% url 'cag:agencias' %}"><span class="fa fa-home"></span> Agências</a></li>
            <li class="xn-openable">
                <a href="#"><span class="fa fa-table"></span> <span class="xn-text">Infra-Estrutura</span></a>
                <ul>
                    <li><a href="{% url 'cag:links' %}"><span class="fa fa-signal"></span> Links</a></li>
                </ul>
            </li>
        </ul>
    </li>
    <li class="xn-openable">
        <a href="#"><span class="fa fa-desktop"></span> <span class="xn-text">Pex</span></a>
        <ul>
            <li><a href="{% url 'cag:tipos' %}"><span class="fa fa-bookmark"></span> Tipologias</a></li>
            <li><a href="{% url 'cag:pas' %}"><span class="fa fa-group"></span> PA's</a></li>
        </ul>
    </li>
    <li class="xn-openable">
        <a href="#"><span class="fa fa-users"></span> <span class="xn-text">Pessoas/Atendentes</span></a>
        <ul>
            <li><a href="{% url 'cat:cargos' %}"><span class="fa fa-table"></span> Cargos</a></li>
            <li><a href="{% url 'cat:pessoas' %}"><span class="fa fa-users"></span> Pessoas</a></li>
            <li><a href="{% url 'cat:atendentes' %}"><span class="fa fa-users"></span> Atendentes</a></li>
        </ul>
    </li>
    <li class="xn-openable">
        <a href="#"><span class="fa fa-tasks"></span> <span class="xn-text">Treinamentos</span></a>
        <ul>
            <li><a href="{% url 'ctr:treinamentos' %}"><span class="fa fa-table"></span> Treinamentos</a></li>
            <li><a href="{% url 'ctr:pesquisa_matricula' %}"><span class="fa fa-table"></span> Localizar matricula</a></li>
        </ul>
    </li>
</ul>

core/templates/table.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block container %}

    <!-- PAGE CONTENT WRAPPER -->
    <div class="page-content-wrap">

        <div class="row">
            <div class="col-md-12">

                <!-- START DATATABLE EXPORT -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{% block titulo_container %} {% endblock %}</h3>
                        <div class="btn-group pull-right">
                            {% block add_buttons %} {% endblock %}
                            <button class="btn btn-danger dropdown-toggle" data-toggle="dropdown"><i
                                    class="fa fa-bars"></i>
                                Exportar dados
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#"
                                       onClick="$('#td_padrao').tableExport({type:'json',escape:'false'});"><img
                                        src='{% static 'img/icons/json.png' %}' width="24"/> JSON</a></li>
                                <li><a href="#"
                                       onClick="$('#td_padrao').tableExport({type:'json',escape:'false',ignoreColumn:'[2,3]'});"><img
                                        src='{% static 'img/icons/json.png' %}' width="24"/> JSON (ignoreColumn)</a>
                                </li>
                                <li><a href="#" onClick="$('#td_padrao').tableExport({type:'json',escape:'true'});"><img
                                        src='{% static 'img/icons/json.png' %}' width="24"/> JSON (with Escape)</a></li>
                                <li class="divider"></li>
                                <li><a href="#" onClick="$('#td_padrao').tableExport({type:'xml',escape:'false'});"><img
                                        src='{% static 'img/icons/xml.png' %}' width="24"/> XML</a></li>
                                <li><a href="#" onClick="$('#td_padrao').tableExport({type:'sql'});"><img
                                        src='{% static 'img/icons/sql.png' %}'
                                        width="24"/> SQL</a></li>
                                <li class="divider"></li>
                                <li><a href="#" onClick="$('#td_padrao').tableExport({type:'csv',escape:'false'});"><img
                                        src='{% static 'img/icons/csv.png' %}' width="24"/> CSV</a></li>
                                <li><a href="#" onClick="$('#td_padrao').tableExport({type:'txt',escape:'false'});"><img
                                        src='{% static 'img/icons/txt.png' %}' width="24"/> TXT</a></li>
                                <li class="divider"></li>
                                <li><a href="#"
                                       onClick="$('#td_padrao').tableExport({type:'excel',escape:'false'});"><img
                                        src='{% static 'img/icons/xls.png' %}' width="24"/> XLS</a></li>
                                <li><a href="#" onClick="$('#td_padrao').tableExport({type:'doc',escape:'false'});"><img
                                        src='{% static 'img/icons/word.png' %}' width="24"/> Word</a></li>
                                <li><a href="#"
                                       onClick="$('#td_padrao').tableExport({type:'powerpoint',escape:'false'});"><img
                                        src='{% static 'img/icons/ppt.png' %}' width="24"/> PowerPoint</a></li>
                                <li class="divider"></li>
                                <li><a href="#" onClick="$('#td_padrao').tableExport({type:'png',escape:'false'});"><img
                                        src='{% static 'img/icons/png.png' %}' width="24"/> PNG</a></li>
                                <li><a href="#" onClick="$('#td_padrao').tableExport({type:'pdf',escape:'false'});"><img
                                        src='{% static 'img/icons/pdf.png' %}' width="24"/> PDF</a></li>
                            </ul>
                        </div>

                    </div>
                    <div class="panel-body">
                        <table id="td_padrao" class="table datatable">
                            <thead>
                            {% block head_table %} {% endblock %}
                            </thead>
                            <tbody>
                            {% block body_table %} {% endblock %}
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
        <!-- END DATATABLE EXPORT -->
    </div>
    <!-- END PAGE CONTENT WRAPPER -->

{% endblock %}

{% block code_scripts %}
    <script type="text/javascript" src="{% static "js/plugins/datatables/jquery.dataTables.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/plugins/tableexport/tableExport.js" %}"></script>
    <script type="text/javascript" src="{% static "js/plugins/tableexport/jquery.base64.js" %}"></script>
    <script type="text/javascript" src="{% static "js/plugins/tableexport/html2canvas.js" %}"></script>
    <script type="text/javascript" src="{% static "js/plugins/tableexport/jspdf/libs/sprintf.js" %}"></script>
    <script type="text/javascript" src="{% static "js/plugins/tableexport/jspdf/jspdf.js" %}"></script>
    <script type="text/javascript" src="{% static "js/plugins/tableexport/jspdf/libs/base64.js" %}"></script>
{% endblock %}

core/templates/top.html
{% load staticfiles %}

<ul class="x-navigation x-navigation-horizontal x-navigation-panel">
    <!-- TOGGLE NAVIGATION -->
    <li class="xn-icon-button">
        <a href="#" class="x-navigation-minimize"><span class="fa fa-dedent"></span></a>
    </li>
    <!-- END TOGGLE NAVIGATION -->
    <!-- SEARCH -->
    <li class="xn-search">
        <form role="form">
            <input type="text" name="search" placeholder="Localizar..."/>
        </form>
    </li>
    <!-- END SEARCH -->
    <!-- SIGN OUT -->
    <li class="xn-icon-button pull-right">
        <a href="#" class="mb-control" data-box="#mb-signout"><span class="fa fa-sign-out"></span></a>
    </li>
    <!-- END SIGN OUT -->
</ul>