cag/urls.py
#coding=utf-8
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^empresa/$', views.empresas, name="empresas"),
    url(r'^regional/$', views.regionais, name="regionais"),
    url(r'^baseregional/$', views.basesregionais, name="basesregionais"),
    url(r'^pex/$', views.tipos, name="tipos"),
    url(r'^pex/pas/$', views.pas, name="pas"),
    url(r'^infraestrutura/link/$', views.links, name="links"),
    url(r'^agencias/$', views.agencias, name="agencias"),
    url(r'^agencias/detalhes/(?P<pk>[\w_-]+)/$', views.agencia_detalhes, name="agencia_detalhes"),
]

ctr/urls.py
#coding=utf-8
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^treinamento/$', views.treinamentos, name="treinamentos"),
    url(r'^treinamento/inicial/add/$', views.treinamento_inicial_add, name="treinamento_inicial_add"),
    url(r'^treinamento/inicial/update/(?P<pk>\d+)/$', views.treinamento_inicial_update, name='treinamento_inicial_update'),
    url(r'^treinamento/rotina/add/$', views.treinamento_rotina_add, name="treinamento_rotina_add"),
    url(r'^treinamento/rotina/update/(?P<pk>\d+)/$', views.treinamento_rotina_update,
        name='treinamento_rotina_update'),
    url(r'^matriculados/(?P<treinamento_pk>\d+)/$', views.matriculas_treinamento, name='avaliar_treinamento'),
    url(r'^matriculado/(?P<pk>\d+)/treinamento/(?P<treinamento_pk>\d+)/$', views.avaliar_matriculado, name='avaliar_matriculado'),
    url(r'^pesquisa_matricula/$', views.pesquisa_matricula, name='pesquisa_matricula'),
]

gestao/urls.py
#coding=utf-8
from copy import name

from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.views.static import serve as serve_static

from core import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^controle_agencias/', include('cag.urls', namespace='cag')),
    url(r'^controle_pessoas/', include('cat.urls', namespace='cat')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^controle_treinamentos/', include('ctr.urls', namespace='ctr')),
    url(r'^admin/', admin.site.urls),
    url(r'^entrar/$', login, {'template_name' : 'login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page' : '/'}, name='logout'),    
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

ctr/models.py
#coding=utf-8
from datetime import date
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse_lazy
from django.utils.safestring import mark_safe

from core.models import ControleTemporal
from core.lists import SITUACAO_CHOICES
from .lists import SITUACAO_AVALIACAO_CHOICES, SITUACAO_TREINAMENTO_CHOICES

class Prazo(ControleTemporal):

    nome = models.CharField(max_length=15, unique=True)
    qtd_dia = models.IntegerField('Quantidade de dias')
    dia_util = models.BooleanField(verbose_name='Dia útil', default=False, help_text='Contabilizar apenas os dias úteis')
    qtd_prova = models.PositiveIntegerField('Quantidade de provas', default=2)

    class Meta:
        ordering = ['nome']

    def __str__(self):
        return self.nome

class Treinamento(ControleTemporal):

    TIPO_TREINAMENTO = (
        ('inicial', 'Inicial'),
        ('rotina', 'Rotina'),
    )

    titulo = models.CharField('Título', max_length=50, help_text="Deve ter até 50 caracteres.")
    descricao = models.TextField('Descrição', null=True, blank=True)
    tipo = models.CharField(max_length=25, choices=TIPO_TREINAMENTO)
    prazo = models.ForeignKey(Prazo)
    status = models.CharField(max_length=2, choices=SITUACAO_TREINAMENTO_CHOICES, default='EM')
    empresa = models.ForeignKey('cag.Empresa', related_name='emp_tre', null=True, blank=True)

    class Meta:
        ordering = ['titulo']

    def __str__(self):
        return '{} [{}]'.format(self.titulo, self.titulo)

    def get_matriculados_count(self):
        return self.treinamentos.count()

    def get_matricular_no_treinamento(self):
        if self.tipo == 'inicial':
            return reverse_lazy('ctr:treinamento_inicial_update', kwargs=dict(pk=self.id))
        else:
            return reverse_lazy('ctr:treinamento_rotina_update', kwargs=dict(pk=self.id))

    def get_ver_matriculados(self):
        return reverse_lazy('ctr:avaliar_treinamento', kwargs=dict(treinamento_pk=self.pk))

class Matricula(ControleTemporal):

    treinamento = models.ForeignKey(Treinamento, related_name='treinamentos')
    pessoa = models.ForeignKey('cat.Pessoa', related_name='pessoas')
    status = models.CharField(max_length=15,
                              choices=SITUACAO_AVALIACAO_CHOICES, default='naoavaliado')

    class Meta:
        ordering = ['treinamento', 'pessoa']
        unique_together = ('treinamento', 'pessoa')

    def __str__(self):
        return '{}'.format(self.pk)

    def get_qtd_provas_lancadas(self):
        return self.matriculas.count()

#    def get_status_matriculado(self):
#        avaliados = self.matriculas.count()
#        if avaliados <= 0:
#            return 'Não avaliado'
#        else:
#            return avaliados

    def get_status(self):
        retorno = None
        if self.status == 'naoavaliado':
            retorno = '<span class="label label-primary label-form">Não avaliado</span>'
        elif self.status == 'aprovado':
            retorno = '<span class="label label-success label-form">Aprovado</span>'
        elif self.status == 'reprovado':
            retorno = '<span class="label label-danger label-form">Reprovado</span>'
        else:
            retorno = '<span class="label label-warning label-form">Recuperação</span>'

    def get_disponibilidade(self):
        lancadas = self.get_qtd_provas_lancadas()
        qtd_prova = self.treinamento.prazo.qtd_prova
        return lancadas >= qtd_prova

    def get_absolute_url(self):
        if self.status != 'aprovado' or self.status != 'reprovado':
            return reverse_lazy('ctr:avaliar_matriculado',
                            kwargs=dict(treinamento_pk=self.treinamento.pk,
                                                                   pk=self.pk
                                        ))

    def save(self, *args, **kwargs):
        super(Matricula, self).save(*args, **kwargs)
        pk_treinamento = self.treinamento_id
        qtd_matriculas_pendentes = Treinamento.objects.filter(pk=pk_treinamento).prefetch_related('treinamentos').filter(treinamentos__status__in=['naoavaliado', 'recuperacao']).count()
        if qtd_matriculas_pendentes == 0:
            treinamento = Treinamento.objects.get(pk=pk_treinamento)
            treinamento.status = 'CO'
            treinamento.save()

class Avaliacao(ControleTemporal):

    matricula = models.ForeignKey(Matricula, related_name='matriculas')
    status = models.CharField(max_length=15,
                              choices=SITUACAO_AVALIACAO_CHOICES, default='naoavaliado')
    nota = models.FloatField('Nota da prova', default=0.00, help_text=u'Informe a nota da prova.')
    prova = models.FileField('Arquivo da prova',
                             upload_to='avaliacoes/provas', help_text=u'Envie a prova.')

    def get_status(self):
        retorno = None
        if self.status == 'naoavaliado':
            retorno = '<span class="label label-primary label-form">Não avaliado</span>'
        elif self.status == 'aprovado':
            retorno = '<span class="label label-success label-form">Aprovado</span>'
        elif self.status == 'reprovado':
            retorno = '<span class="label label-danger label-form">Reprovado</span>'
        else:
            retorno = '<span class="label label-warning label-form">Recuperação</span>'
        return mark_safe(retorno)

    def get_disponibilidade(self):
        lancadas = Avaliacao.objects.filter(matricula=self.matricula).count()
        qtd_prova = self.matricula.treinamento.prazo.qtd_prova
        return lancadas >= qtd_prova

    def get_qtd_provas(self):
        return self.matricula.treinamento.prazo.qtd_prova

    def __str__(self):
        return '{} [{}]'.format(self.matricula, self.status)

    def save(self, *args, **kwargs):
        status = None
        if self.get_disponibilidade():
            raise ValidationError('Não há mais disponibilidade de provas.')
        else:
            # status = None
            pk_matricula = self.matricula_id

            if self.nota >= float(8):
                status = 'aprovado'
            elif self.nota < float(8) and self.matricula.get_qtd_provas_lancadas() == 0:
                status = 'recuperacao'
            else:
                status = 'reprovado'
            self.status = status
        super(Avaliacao, self).save(*args, **kwargs)
        mat = Matricula.objects.get(pk=pk_matricula)
        mat.status = status
        mat.save(force_update=True)



    class Meta:
        verbose_name = 'Avaliação'
        verbose_name_plural = 'Avaliações'

ctr/views.py
#coding=utf-8

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.shortcuts import get_object_or_404, redirect, render_to_response
from django.views.generic import TemplateView

from .forms import *
from .models import Treinamento, Matricula

from extra_views import InlineFormSet, CreateWithInlinesView, UpdateWithInlinesView
from extra_views import NamedFormsetsMixin

class AvaliacaoInline(InlineFormSet):
    model = Avaliacao
    fields = ['nota', 'prova']
    extra = 1
    formset_class = get_avaliacao_formset()

    def get_formset(self):
        treinamento = get_object_or_404(Treinamento, pk=self.kwargs.get('treinamento_pk'))
        self.max_num = treinamento.prazo.qtd_prova
        return super(AvaliacaoInline, self).get_formset()

class MatriculaAvaliacao(LoginRequiredMixin, NamedFormsetsMixin, UpdateWithInlinesView):
    template_name = 'ctr/matriculas/avaliar_matriculado.html'
    model = Matricula
    form_class = MatriculaAvaliacaoForm
    inlines = [AvaliacaoInline]
    inlines_names = ['formset']

    def get_success_url(self):
        return reverse_lazy('ctr:avaliar_treinamento', kwargs=dict(treinamento_pk=self.kwargs.get('treinamento_pk')))


class MatriculaInicialInline(InlineFormSet):
    model = Matricula
    fields = ['pessoa']
    extra = 1
    formset_class = get_matricula_formset_inicial()
    form_class = MatriculaInicialForm

class TreinamentoInicialCreateView(LoginRequiredMixin, NamedFormsetsMixin, CreateWithInlinesView):
    template_name = 'ctr/matriculas/efetuar_matricula.html'
    model = Treinamento
    form_class = TreinamentoForm
    initial = dict(tipo='inicial')
    inlines = [MatriculaInicialInline]
    inlines_names = ['formset']

    def get_success_url(self):
        return reverse_lazy('ctr:treinamentos')

    def get_context_data(self, **kwargs):
        context = super(TreinamentoInicialCreateView, self).get_context_data(**kwargs)
        context['titulo'] = 'Novo treinamento inicial'
        return context

    def get_form_kwargs(self):
        kwargs = super(TreinamentoInicialCreateView, self).get_form_kwargs()
        kwargs['ocultar'] = True
        kwargs['empresa'] = self.request.user.profile.empresa
        return kwargs

class MatriculaRotinaInline(InlineFormSet):
    model = Matricula
    fields = ['pessoa']
    extra = 1
    formset_class = get_matricula_formset_rotina()
    form_class = MatriculaRotinaForm

class TreinamentoRotinaCreateView(LoginRequiredMixin, NamedFormsetsMixin, CreateWithInlinesView):
    template_name = 'ctr/matriculas/efetuar_matricula.html'
    model = Treinamento
    form_class = TreinamentoForm
    initial = dict(tipo='rotina')
    inlines = [MatriculaRotinaInline]
    inlines_names = ['formset']

    def get_success_url(self):
        return reverse_lazy('ctr:treinamentos')

    def get_context_data(self, **kwargs):
        context = super(TreinamentoRotinaCreateView, self).get_context_data(**kwargs)
        context['titulo'] = 'Novo treinamento de rotina'
        return context

    def get_form_kwargs(self):
        kwargs = super(TreinamentoRotinaCreateView, self).get_form_kwargs()
        kwargs['ocultar'] = True
        kwargs['empresa'] = self.request.user.profile.empresa
        return kwargs

class TreinamentoInicialUpdateView(LoginRequiredMixin, NamedFormsetsMixin, UpdateWithInlinesView):
    template_name = 'ctr/matriculas/update_matricula.html'
    model = Treinamento
    form_class = TreinamentoUpdateForm
    inlines = [MatriculaInicialInline]
    inlines_names = ['formset']

    def get_context_data(self, **kwargs):
        context = super(TreinamentoInicialUpdateView, self).get_context_data(**kwargs)
        context['titulo'] = 'Alterar treinamento inicial'
        return context

    def get_success_url(self):
        return reverse_lazy('ctr:treinamentos')


class TreinamentoRotinaUpdateView(LoginRequiredMixin, NamedFormsetsMixin, UpdateWithInlinesView):
    template_name = 'ctr/matriculas/update_matricula.html'
    model = Treinamento
    form_class = TreinamentoUpdateForm
    inlines = [MatriculaRotinaInline]
    inlines_names = ['formset']

    def get_context_data(self, **kwargs):
        context = super(TreinamentoRotinaUpdateView, self).get_context_data(**kwargs)
        context['titulo'] = 'Alterar treinamento de rotina'
        return context

    def get_success_url(self):
        return reverse_lazy('ctr:treinamentos')

class TreinamentoList(LoginRequiredMixin, ListView):

    template_name = 'ctr/treinamentos/treinamentos.html'
    model = Treinamento
    context_object_name = 'treinamentos'

    def get_queryset(self):
        return super(TreinamentoList, self).get_queryset().prefetch_related('treinamentos').filter(empresa__id=self.request.user.profile.empresa_id)

class MatriculasTreinamentoList(LoginRequiredMixin, ListView):

    template_name = 'ctr/matriculas/matriculas.html'
    model = Matricula
    context_object_name = 'matriculas'

    def get_queryset(self):
        treinamento = get_object_or_404(Treinamento, pk=self.kwargs['treinamento_pk'])
        return super(MatriculasTreinamentoList, self).get_queryset().prefetch_related('matriculas').select_related('treinamento', 'pessoa').filter(treinamento=treinamento)

class MatriculaList(LoginRequiredMixin, ListView):

    template_name = 'ctr/matriculas/pesquisar_matriculas.html'
    model = Matricula
    context_object_name = 'matriculas'

    def get_queryset(self):
        titulo = self.request.GET.get('treinamento', False)
        nome = self.request.GET.get('pessoa', False)
        matricula = self.request.GET.get('matricula', False)

        empresa = self.request.user.profile.empresa_id
        queryset = super(MatriculaList, self).get_queryset().select_related('treinamento', 'pessoa').filter(treinamento__empresa_id=empresa)
        if titulo:
            return queryset.filter(treinamento__titulo__icontains=titulo)
        elif nome:
            return queryset.filter(pessoa__nome__icontains=nome)
        elif matricula:
            return queryset.filter(pessoa__pessoa__matricula__startswith=matricula)
        else:
            return None


treinamentos = TreinamentoList.as_view()
treinamento_inicial_add = TreinamentoInicialCreateView.as_view()
treinamento_inicial_update = TreinamentoInicialUpdateView.as_view()
treinamento_rotina_add = TreinamentoRotinaCreateView.as_view()
treinamento_rotina_update = TreinamentoRotinaUpdateView.as_view()
matriculas_treinamento = MatriculasTreinamentoList.as_view()
avaliar_matriculado = MatriculaAvaliacao.as_view()
pesquisa_matricula = MatriculaList.as_view()

ctr/templates/ctr/matriculas/avaliar_matriculado.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load widget_tweaks %}

{% block css_or_script_head %}
{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li><a href="#">Controle de Treinamentos</a></li>
    <li>Treinamento & Matricula</li>
    <li class="active">Realizar avaliação</li>
{% endblock %}

{% block container %}
    <div class="page-content-wrap">

        <div class="row">
            <div class="col-md-12">

                <form id="form_tre" enctype="multipart/form-data" class="form-horizontal" method="post" role="form">
                    {% csrf_token %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><strong>Avaliação</strong></h3>
                            <ul class="panel-controls">
                                <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
                            </ul>
                        </div>
                        <div class="panel-body">
                            {% for field in form %}
                                <div class="form-group {% if field.errors %} has-error {% endif %}">
                                    <label class="col-md-3 col-xs-12 control-label"
                                           for="{{ field.auto_id }}">{{ field.label }}</label>
                                    <div class="col-md-6 col-xs-12">
                                        {% if field.label == 'Tipo' or field.label == 'Prazo' %}
                                            {% render_field field class='form-control' %}
                                        {% elif field.label == 'Título' %}
                                            <div class="input-group">
                                                <span class="input-group-addon"><span
                                                        class="fa fa-pencil"></span></span>
                                                {% render_field field class='form-control' %}
                                            </div>
                                        {% else %}
                                            {% render_field field class='form-control' %}
                                        {% endif %}
                                        <span class="help-block">{{ field.help_text }}</span>
                                    </div>
                                </div>
                            {% endfor %}
                            {{ formset.management_form }}
                            {% for form in formset %}
                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger alert-dismissible">
                                        <button type="button" class="close" data-dismiss="alert"
                                                aria-hidden="true">&times;</button>
                                        <h3><i class="icon fa fa-ban"></i> Erro!</h3>
                                        {{ error }}
                                    </div>
                                {% endfor %}
                                <div class="inline {{ formset.prefix }}">
                                    {{ form.id }}
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label"
                                               for="{{ form.nota.tag_label }}">{{ form.nota.label }}</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span
                                                        class="glyphicon glyphicon-book"></span></span>
                                                {{ form.nota|add_class:'form-control'|attr:"required" }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label"
                                               for="{{ form.prova.tag_label }}">{{ form.prova.label }}</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span
                                                        class="fa fa-file-text-o"></span></span>
                                                {{ form.prova|add_class:'form-control' }}
                                            </div>
                                        </div>
                                    </div>
                                    <span>
                                        {{ form.id }}
                                        {{ form.DELETE }}
                                    </span>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="panel-footer">
                            <a class="btn btn-default" href="{% url 'ctr:treinamentos' %}"
                               title="Retorna para a página de treinamentos.">Voltar</a>
                            <button type="submit" class="btn btn-primary">Salvar</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>

    </div>
    <!-- END PAGE CONTENT WRAPPER -->
{% endblock %}

{% block scripts_body %}
    <script type="text/javascript" src="{% static "js/plugins/formset/jquery.formset.js" %}"></script>
{% endblock %}

{% block code_scripts %}

    <script type="text/javascript">
        $(document).ready(function () {
            $(".inline.{{ formset.prefix }}").formset({
                prefix: "{{ formset.prefix }}",
                addText: "adicionar pessoa",
                deleteText: "remover"
            });

            $(".add-row").attr('class', 'btn btn-primary btn-rounded ').attr('onclick', "$('.delete-row').addClass('btn btn-danger btn-rounded').css('float', 'right').css('margin-top', '-3.8%').css('margin-right', '17%');");

            ajustarBotaoDelete();

            function ajustarBotaoDelete() {
                $(".delete-row").addClass('btn btn-danger btn-rounded').css('float', 'right').css('margin-top', '-1%').css('margin-right', '25%');
            }

        });

    </script>

{% endblock %}

ctr/templates/ctr/matriculas/efetuar_matricula.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load widget_tweaks %}

{% block css_or_script_head %}
    <!-- Select2 -->
    <link href="{% static "js/plugins/select2/dist/css/select2.min.css" %}" rel="stylesheet">
{% endblock %}


{% block container %}
    <div class="page-content-wrap">

        <div class="row">
            <div class="col-md-12">

                <form id="form_tre" class="form-horizontal" method="post" role="form">
                    {% csrf_token %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><strong>{{ titulo }}</strong></h3>
                            <ul class="panel-controls">
                                <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
                            </ul>
                        </div>
                        <div class="panel-body">
                            {% for field in form %}
                                <div class="form-group {% if field.errors %} has-error {% endif %}">
                                    <label class="col-md-3 col-xs-12 control-label"
                                           for="{{ field.auto_id }}">{{ field.label }}</label>
                                    <div class="col-md-6 col-xs-12">
                                        {% if field.label == 'Tipo' or field.label == 'Prazo' %}
                                            {% render_field field class='form-control select2_single' %}
                                        {% elif field.label == 'Título' %}
                                            <div class="input-group">
                                                <span class="input-group-addon"><span
                                                        class="fa fa-pencil"></span></span>

                                                {% render_field field class='form-control' %}
                                            </div>
                                        {% else %}
                                            {% render_field field class='form-control' %}
                                        {% endif %}
                                        <span class="help-block">{{ field.help_text }}</span>
                                        {% if field.errors %}<p class="help-block">
                                            {% for error in field.errors %}{{ error }}{% endfor %}</p>{% endif %}
                                    </div>
                                </div>
                            {% endfor %}
                            {{ formset.management_form }}
                            {% for form in formset %}
                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger alert-dismissible">
                                        <button type="button" class="close" data-dismiss="alert"
                                                aria-hidden="true">&times;</button>
                                        <h3><i class="icon fa fa-ban"></i> Erro!</h3>
                                        {{ error }}
                                    </div>
                                {% endfor %}
                                {{ form.id }}
                                <div class="inline {{ formset.prefix }} form-group">
                                    <label class="col-md-3 col-xs-12 control-label"
                                           for="{{ form.pessoa.tag_label }}">{{ form.pessoa.label }}</label>
                                    <div class="col-md-6 col-xs-12">
                                        {% render_field form.pessoa class='select2_single form-control' tabindex="-1" %}
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="panel-footer">
                            <a class="btn btn-default" href="{% url 'ctr:treinamentos' %}"
                               title="Retorna para a página de treinamentos.">Voltar</a>
                            <button type="submit" class="btn btn-primary">Salvar</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>

    </div>
    <!-- END PAGE CONTENT WRAPPER -->
{% endblock %}

{% block scripts_body %}
    <script type="text/javascript" src="{% static "js/plugins/formset/jquery.formset.js" %}"></script>
    <!-- Select2 -->
    <script src="{% static "js/plugins/select2/dist/js/select2.full.min.js" %}"></script>
{% endblock %}

{% block code_scripts %}

    <script type="text/javascript">
        $(document).ready(function () {
            $(".inline.{{ formset.prefix }}").formset({
                prefix: "{{ formset.prefix }}",
                addText: "adicionar pessoa",
                deleteText: "remover"
            });

            $(".delete-row").addClass('btn btn-danger btn-rounded');

            $(".select2_single").select2({
                placeholder: "Selecione uma pessoa.",
                allowClear: true
            });

            $("#id_prazo").select2({placeholder: 'Selecione um tipo de prazo.'});

            $(".add-row").on("click", function () {
                $(".select2_single").select2({
                    placeholder: "Selecione uma pessoa.",
                    allowClear: true
                });
                $("#id_prazo").select2({placeholder: 'Selecione um tipo de prazo.'});
            });
            $(".add-row").attr('class', 'btn btn-primary btn-rounded ').attr('onclick', "$('.delete-row').addClass('btn btn-danger btn-rounded');");

        });
    </script>

{% endblock %}

ctr/templates/ctr/matriculas/matriculas.html
{% extends 'table.html' %}

{% block breadcrumb %}
    {{ block.super }}
    <li><a href="{% url 'ctr:treinamentos' %}">Treinamentos</a></li>
    <li class="active">Matriculados</li>
{% endblock %}

{% block titulo_container %}
    Matriculados
{% endblock %}

{% block head_table %}
    <tr>
        <th>#</th>
        <th>Treinamento</th>
        <th>Pessoa/Atendente</th>
        <th>Status</th>
        <th></th>
    </tr>
{% endblock %}

{% block body_table %}
    {% for matricula in matriculas %}
        <tr>
            <td>{{ matricula.pk }}</td>
            <td>
                {{ matricula.treinamento.titulo }}
            </td>
            <td>
                <a href="{{ matricula.get_absolute_url }}" class="btn-link">
                    {{ matricula.pessoa }}
                </a>
            </td>
            <td>
                <span class="label label-info label-form">
                    {% comment %}{% if matricula.get_status_matriculado > 1 %}
                        Avaliações realizadas
                    {% elif matricula.get_status_matriculado == 1 %}
                        Avaliação realizada
                    {% else %}
                        {{ matricula.get_status_matriculado }}
                    {% endif %}{% endcomment %}
                    {% if matricula.status == 'naoavaliado' %}
                        Não avaliado
                    {% elif matricula.status == 'aprovado' %}
                        Aprovado
                    {% elif matricula.status == 'recuperacao' %}
                        Recuperação
                    {% elif matricula.status == 'reprovado' %}
                        Reprovado
                    {% endif %}
                </span>
            </td>
            <td>
                {% if matricula.get_qtd_provas_lancadas >= 1 %}
                    {% for a in matricula.matriculas.all %}
                        {{ a.get_status }}
                    {% endfor %}
                {% endif %}
            </td>
        </tr>
    {% endfor %}
{% endblock %}